[package]
name = "tauri-trunk-template"
version = "0.1.0"
edition = "2018"
readme = "README.md"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.76"
wee_alloc = "0.4.5"